ARROW-7187: [C++][Doc] doxygen broken on master because of @
https://github.com/apache/arrow/runs/305621760#step:5:985

```
/arrow/cpp/src/arrow/dataset/discovery.h:159: error: Found unknown command `\FileSystemDiscoveryOptions' (warning treated as error, aborting now)
```

Closes #5848 from nealrichardson/fix-dataset-docs and squashes the following commits:

a6a19010c <Neal Richardson> Remove @ that appears to break doxygen

Authored-by: Neal Richardson <neal.p.richardson@gmail.com>
Signed-off-by: Neal Richardson <neal.p.richardson@gmail.com>