ARROW-15532: [C++] Fix unused warning for StringClassifyDoc
Following conversion with @lidavidm on mailing list. This should get rid of the warning:

```
/Users/icexelloss/workspace/arrow/cpp/src/arrow/compute/kernels/scalar_string_internal.h:216:20: error: unused function 'StringClassifyDoc' [-Werror,-Wunused-function]

static FunctionDoc StringClassifyDoc(std::string class_summary, std::string class_desc,
```

Closes #12321 from icexelloss/ARROW-15532

Authored-by: Li Jin <ice.xelloss@gmail.com>
Signed-off-by: Li Jin <ice.xelloss@gmail.com>