ARROW-8622: [Rust] Allow the parquet crate to be compiled on aarch64 platforms
The following compile error shows up on aarch64 because the body of `hash_` was `#cfg`'d to basically empty.

```
    error[E0308]: mismatched types
      --> /home/tyler/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/b7421bb/rust/parquet/src/util/hash_util.rs:26:37
       |
    26 | fn hash_(data: &[u8], seed: u32) -> u32 {
       |    -----                            ^^^ expected `u32`, found `()`
       |    |
       |    implicitly returns `()` as its body has no tail or `return` expression

    error: aborting due to previous error
```

Closes #7059 from rtyler/aarch64-fixes

Authored-by: R. Tyler Croy <rtyler@brokenco.de>
Signed-off-by: Paddy Horan <paddyhoran@hotmail.com>