ARROW-2812: [Ruby] Fix Arrow::Array#[] interface for Arrow::StructArray
`Arrow::StructArray` does not have `#get_value` method, and `Arrow::Array#[]` interface depends on `#get_value` method.

And so, `StructArray` cannot access internal columns via `#[]` interface.

Error message is following.

```
NoMethodError: undefined method `get_value' for #<Arrow::StructArray:0x0000000001859ac0>
```

This patch fixes it.

Author: joker1007 <kakyoin.hierophant@gmail.com>
Author: Kouhei Sutou <kou@clear-code.com>

Closes #2233 from joker1007/fix-array-interface-for-struct-array and squashes the following commits:

36d1d819 [Kouhei Sutou] Fix wrong affected check
1083e843 [joker1007] ARROW-2812: [Ruby] Fix Arrow::Array#[] interface for Arrow::StructArray